#!/usr/bin/env sh

set -e

TARGET_DIR=/tmp/test

mkdir -p ${TARGET_DIR}

protoc-wrapper \
  -I/usr/include \
  --php_out=${TARGET_DIR} \
  --grpc-php_out=${TARGET_DIR} \
  --php-grpc_out=${TARGET_DIR} \
  --js_out=import_style=commonjs,binary:${TARGET_DIR} \
  --es_out=${TARGET_DIR} --es_opt target=ts \
  --cpp_out=${TARGET_DIR} \
  --csharp_out=${TARGET_DIR} \
  --java_out=${TARGET_DIR} \
  --kotlin_out=${TARGET_DIR} \
  --objc_out=${TARGET_DIR} \
  --pyi_out=${TARGET_DIR} \
  --python_out=${TARGET_DIR} \
  --ruby_out=${TARGET_DIR} \
  google/protobuf/any.proto

rm -rf ${TARGET_DIR}